### ISSUE TITLE
Wrong image name in Dockerfile

### ISSUE THREAD

**Issue by GoranBosevski** [driftphp/demo#6]
Original:
FROM driftphp:base
It fails, with error:

repository does not exist or may require 'docker login'

It should be:

FROM driftphp/base

That fixed it for me.

Great job guys.

**Comment by mmoreram** [comment]
Hello @GoranBosevski 

You're right!
That's an important issue :)
May I ask you to send us a PR? That would make you part of the project :D

Thanks so much for finding the bug!

**Comment by GoranBosevski** [comment]
Thanks again for the work you are putting in this project! 

PR sent and merged, this is fixed now.

**Comment by mmoreram** [comment]
Thanks so much @GoranBosevski for your feedback :)
I'm so happy to be working on this :)
I hope you're enjoying!
